package MVC;

public enum Etat {
    LECTURE,
    AJOUTER_SURFACE,
    ETIRER_SURFACE,
    DEPLACER_SURFACE,
    CREER_FORME_LIBRE,
    ALIGNER,
    OUVRIR_FENETRE_ALIGNER,
    SELECTIONNER_ALIGNER,
    FUSIONNER,
}
